import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css" ;
import ClientProvider from "./clientProvider";
import ClientInitializer from "./clientInitializer";
import NavUser from "./components/navUser";
import NavBar from "./components/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh`}
      >
        <ClientProvider>
          <ClientInitializer >
            <nav className="h-1/19 z-10">
              <NavBar />
            </nav>
            <main className="h-18/19">
              {children}
            </main>
          </ClientInitializer>
        </ClientProvider>
      </body>
    </html>
  );
}
